### ISSUE TITLE
Problem with calculate_AA_variation function

### ISSUE THREAD

**Issue by maribzo** [michaelllo1993/BALCONY#9]
**Describe the bug**
I have a problem with calculating calculate_AA_variation function. It seemed to work with my previous alignment, but for the new one (which differs only in amount of the sequences) it doesn't work. I checked  if the amounts of number of sequences and number of positions in the alignment in the variables obtained in previous lines of script are ok and everything is fine. Also the file with the alignment looks ok. 

**Output of the `sessionInfo()`**

Error in  '`[<-`(`*tmp*`, j, i, value = mean(weights[which_representative]))':
  index out of range

**To Reproduce**
var_aa = calculate_AA_variation(file, weights = consensus_sequences_distance); 

**Expected behavior**
I expected it to be calculated, because I can not proceed further with my calculations 

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.10
 - Version of the software:
R 3.4.4.
BALCONY 0.2.8.

**Comment by stolarczyk** [comment]
The error was the result of the `X` character presence in the alignment. The `calculate_AA_variation` follows the assumption that only 20 AA and `-`are allowed. 

Now the number `21` is not hard-coded, yet a respective warning is thrown once the aforementioned situation occurs.
